services:
  - type: web
    name: mplads-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn mplads.backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6

  - type: web
    name: mplads-dashboard
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run mplads/dashboard/app.py --server.port $PORT --server.address 0.0.0.0 --server.enableCORS false --server.enableXsrfProtection false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: API_BASE
        fromService:
          type: web
          name: mplads-api
          property: host
